### ISSUE TITLE
Does not work on Windows+Python3

### ISSUE THREAD

**Issue by masahiro-koyanagi** [BeeBeansTechnologies/sitcpy#2]
## How to reproduce
```
cd sitcpy
python setup.py sdist
pip install dist/sitcpy-x.x.x.tar.gz
cd ..

sitcpy createcuiproject myproject
cd myproject
python pseudo.py
```

## Error contents
```
system default encoding:utf-8
Traceback (most recent call last):
  File "pseudo.py", line 106, in <module>
port:9090
    main()
  File "pseudo.py", line 102, in main
    pdev.run_loop()
  File "C:\Users\koyanagi\AppData\Local\Programs\Python\Python37\lib\site-packages\sitcpy\rbcp_server.py", line 939, in run_loop
    self._cuisvr.start()
  File "C:\Users\koyanagi\AppData\Local\Programs\Python\Python37\lib\site-packages\sitcpy\cui.py", line 776, in start
    self._state.wait(sitcpy.THREAD_RUNNING)
  File "C:\Users\koyanagi\AppData\Local\Programs\Python\Python37\lib\site-packages\sitcpy\__init__.py", line 99, in wait
    self._cond.wait(end - now)
  File "C:\Users\koyanagi\AppData\Local\Programs\Python\Python37\lib\threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
OverflowError: timeout value is too large
```

## Cause of the error
Passing a large number (a value that does not fit in int32) to threading.Condition.wait () caused an error.

To simplify the code, I passed a large number instead of None as the timeout value.

**Comment by masahiro-koyanagi** [comment]
Modified to pass None as an argument of Contidion.wait() when there is no timeout limit.
